In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
%matplotlib inline

In [133]:
df=pd.read_csv('Combined_News_DJIA.csv')
df.head()

,Date,Label,Top1,Top2,Top3,Top4,Top5,Top6,Top7,Top8,...,Top16,Top17,Top18,Top19,Top20,Top21,Top22,Top23,Top24,Top25
0,2008-08-08,0,"b""Georgia 'downs two Russian warplanes' as cou...",b'BREAKING: Musharraf to be impeached.',b'Russia Today: Columns of troops roll into So...,b'Russian tanks are moving towards the capital...,"b""Afghan children raped with 'impunity,' U.N. ...",b'150 Russian tanks have entered South Ossetia...,"b""Breaking: Georgia invades South Ossetia, Rus...","b""The 'enemy combatent' trials are nothing but...",...,b'Georgia Invades South Ossetia - if Russia ge...,b'Al-Qaeda Faces Islamist Backlash',"b'Condoleezza Rice: ""The US would not act to p...",b'This is a busy day: The European Union has ...,"b""Georgia will withdraw 1,000 soldiers from Ir...",b'Why the Pentagon Thinks Attacking Iran is a ...,b'Caucasus in crisis: Georgia invades South Os...,b'Indian shoe manufactory - And again in a se...,b'Visitors Suffering from Mental Illnesses Ban...,"b""No Help for Mexico's Kidnapping Surge"""
1,2008-08-11,1,b'Why wont America and Nato help us? If they w...,b'Bush puts foot down on Georgian conflict',"b""Jewish Georgian minister: Thanks to Israeli ...",b'Georgian army flees in disarray as Russians ...,"b""Olympic opening ceremony fireworks 'faked'""",b'What were the Mossad with fraudulent New Zea...,b'Russia angered by Israeli military sale to G...,b'An American citizen living in S.Ossetia blam...,...,b'Israel and the US behind the Georgian aggres...,"b'""Do not believe TV, neither Russian nor Geor...",b'Riots are still going on in Montreal (Canada...,b'China to overtake US as largest manufacturer',b'War in South Ossetia [PICS]',b'Israeli Physicians Group Condemns State Tort...,b' Russia has just beaten the United States ov...,b'Perhaps *the* question about the Georgia - R...,b'Russia is so much better at war',"b""So this is what it's come to: trading sex fo..."
2,2008-08-12,0,b'Remember that adorable 9-year-old who sang a...,"b""Russia 'ends Georgia operation'""","b'""If we had no sexual harassment we would hav...","b""Al-Qa'eda is losing support in Iraq because ...",b'Ceasefire in Georgia: Putin Outmaneuvers the...,b'Why Microsoft and Intel tried to kill the XO...,b'Stratfor: The Russo-Georgian War and the Bal...,"b""I'm Trying to Get a Sense of This Whole Geor...",...,b'U.S. troops still in Georgia (did you know t...,b'Why Russias response to Georgia was right',"b'Gorbachev accuses U.S. of making a ""serious ...","b'Russia, Georgia, and NATO: Cold War Two'",b'Remember that adorable 62-year-old who led y...,b'War in Georgia: The Israeli connection',b'All signs point to the US encouraging Georgi...,b'Christopher King argues that the US and NATO...,b'America: The New Mexico?',"b""BBC NEWS | Asia-Pacific | Extinction 'by man..."
3,2008-08-13,0,b' U.S. refuses Israel weapons to attack Iran:...,"b""When the president ordered to attack Tskhinv...",b' Israel clears troops who killed Reuters cam...,b'Britain\'s policy of being tough on drugs is...,b'Body of 14 year old found in trunk; Latest (...,b'China has moved 10 *million* quake survivors...,"b""Bush announces Operation Get All Up In Russi...",b'Russian forces sink Georgian ships ',...,b'Elephants extinct by 2020?',b'US humanitarian missions soon in Georgia - i...,"b""Georgia's DDOS came from US sources""","b'Russian convoy heads into Georgia, violating...",b'Israeli defence minister: US against strike ...,b'Gorbachev: We Had No Choice',b'Witness: Russian forces head towards Tbilisi...,b' Quarter of Russians blame U.S. for conflict...,b'Georgian president says US military will ta...,b'2006: Nobel laureate Aleksander Solzhenitsyn...
4,2008-08-14,1,b'All the experts admit that we should legalis...,b'War in South Osetia - 89 pictures made by a ...,b'Swedish wrestler Ara Abrahamian throws away ...,b'Russia exaggerated the death toll in South O...,b'Missile That Killed 9 Inside Pakistan May Ha...,"b""Rushdie Condemns Random House's Refusal to P...",b'Poland and US agree to missle defense deal. ...,"b'Will the Russians conquer Tblisi? Bet on it,...",...,b'Bank analyst forecast Georgian crisis 2 days...,"b""Georgia confict could set back Russia's US r...",b'War in the Caucasus is as much the product o...,"b'""Non-media"" photos of South Ossetia/Georgia ...",b'Georgian TV reporter shot by Russian sniper ...,b'Saudi Arabia: Mother moves to block child ma...,b'Taliban wages war on humanitarian aid workers',"b'Russia: World ""can forget about"" Georgia\'s...",b'Darfur rebels accuse Sudan of mounting major...,b'Philippines : Peace Advocate say Muslims nee...

In [31]:
train=df[df['Date']<'2014-01-01']
test=df[df['Date']>'2014-01-01']

In [36]:
trainlines = []
lentrain = len(train.index)
for row in range(0,lentrain):
    trainlines.append(' '.join(str(x) for x in train.iloc[row,2:27]))

In [37]:
from sklearn.feature_extraction.text import CountVectorizer

In [38]:
vect = CountVectorizer()
basictrain = vect.fit_transform(trainlines)
print(basictrain.shape)

(1359, 29493)

In [39]:
from sklearn.linear_model import LogisticRegression

In [42]:
Logreg=LogisticRegression()

In [43]:
Logreg.fit(basictrain,train['Label'])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [48]:
testheadlines = []
for row in range(0,len(test.index)):
    testheadlines.append(' '.join(str(x) for x in test.iloc[row,2:27]))
basictest = vect.transform(testheadlines)
predictions = Logreg.predict(basictest)

In [54]:
predictions

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1], dtype=int64)

In [59]:
from sklearn import metrics

In [62]:
metrics.accuracy_score(test['Label'],predictions)

0.48888888888888887

In [63]:
### 48% prediction

In [66]:
basicwords = vect.get_feature_names()
basiccoeffs = Logreg.coef_.tolist()[0]
coeffdf = pd.DataFrame({'Word' : basicwords, 
                        'Coefficient' : basiccoeffs})
coeffdf = coeffdf.sort_values(['Coefficient', 'Word'], ascending=[0, 1])
coeffdf.head(25)

       Coefficient        Word
26512     0.452770       three
23506     0.450682        self
24497     0.432169          so
10127     0.429720       fears
23873     0.410832        ship
14733     0.401296       kills
5990      0.376924     company
16932     0.376921     missing
2110      0.373610     another
23492     0.372982       seize
20213     0.368077   political
20885     0.356671     protest
26328     0.351606   territory
12780     0.350827    hospital
20814     0.345188  propaganda
28908     0.343494        wing
14872     0.342781       korea
8343      0.340982     doctors
5713      0.340424       coast
27252     0.335777        turn
18723     0.335388    olympics
4728      0.334381    canadian
10623     0.332347       force
27282     0.331350          tv
2440      0.329961    arrested

In [67]:
coeffdf.tail(20)

       Coefficient       Word
3279     -0.352414        bbc
28650    -0.355117    weapons
17440    -0.359312     muslim
3102     -0.359559      banks
25408    -0.365913   students
18971    -0.369939   outbreak
190      -0.371289         17
23662    -0.374962        sex
3369     -0.376173      begin
7898     -0.384709        did
29063    -0.388504  worldwide
12825    -0.394845      hours
25952    -0.399762     system
26032    -0.400850    taliban
26329    -0.414521     terror
11911    -0.416885    hacking
6213     -0.419325      congo
17475    -0.460182         my
23041    -0.526485  sanctions
22838    -0.629666        run

In [108]:
advvect = CountVectorizer(ngram_range=(2,2))

In [109]:
advtrain = advvect.fit_transform(trainlines)

In [110]:
advmodel = LogisticRegression()

In [111]:
advmodel.fit(advtrain,train['Label'])

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [112]:
testlines = []
lentest = len(test.index)
for row in range(0,lentest):
    testlines.append(' '.join(str(x) for x in test.iloc[row,2:27]))

In [113]:
advtest = advvect.transform(testlines)
advpred=advmodel.predict(advtest)

In [114]:
metrics.accuracy_score(test['Label'],advpred)

0.55714285714285716

In [125]:
advwords=advvect.get_feature_names()
advcoeff=advmodel.coef_.tolist()[0]
advdfcoef=pd.DataFrame({'Words':advwords,'Coeffiecient':advcoeff})

In [127]:
advdfcoef=advdfcoef.sort_values(['Coeffiecient','Words'],ascending=[0,1])

In [128]:
advdfcoef.head(20)

        Coeffiecient             Words
137057      0.260295          in china
236720      0.254544          right to
274604      0.248242         the first
21304       0.241296         and other
11958       0.223135         after the
165790      0.220773         likely to
280479      0.217824           this is
119274      0.215517    government has
126163      0.210974           have to
272706      0.208987         that they
247872      0.203556            set to
135014      0.203220           if they
137375      0.201932          in egypt
307606      0.200401          what the
109298      0.199880          found in
91002       0.195814        embassy in
274683      0.193648        the french
245600      0.193067  security council
52485       0.191538         calls for
138841      0.190590          in south

In [129]:
advdfcoef.tail(30)

        Coeffiecient            Words
274841     -0.148084       the ground
296869     -0.148741           us and
52264      -0.152228         call for
256208     -0.152310     south korean
248526     -0.157909         sex with
274769     -0.158662       the german
134913     -0.160248            if it
275373     -0.160841      the largest
138323     -0.160994           in our
70161      -0.161056         could be
8222       -0.161513       accused of
212712     -0.162307    phone hacking
137802     -0.164511          in iran
59161      -0.167178      children in
279401     -0.168373        there was
27416      -0.170483       around the
194375     -0.170491         of human
302051     -0.175163      wall street
272161     -0.176702          that is
279331     -0.177158         there is
284274     -0.181021          to help
38680      -0.184576    been arrested
191406     -0.195420  nuclear weapons
273961     -0.196325      the country
134904     -0.199254            if he
248545     -0.203551     sexual abuse
296018     -0.207047            up in
284516     -0.209831          to kill
42331      -0.217594        bin laden
311993     -0.220734        with iran

In [134]:
a= ' abcd'

In [137]:
a.split